app = "palindromic-fuel"

[build]
  dockerfile = "Dockerfile"

[http_service]
  internal_port = 8080
  force_https = true

  [http_service.concurrency]
    type = "requests"
    soft_limit = 1000
    hard_limit = 1500